# Generated by Django 5.0.2 on 2024-02-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=999)),
                ('precio', models.FloatField(default=0.0)),
                ('codigo', models.CharField(max_length=13)),
            ],
        ),
    ]
