# Generated by Django 5.0.2 on 2024-07-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgField',
            field=models.ImageField(default=None, null=True, upload_to='C:/Users/Administrator/Documents/cicloviasus/viasus/static/'),
        ),
    ]
