# Generated by Django 5.0.2 on 2024-07-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_imgfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgCloud',
            field=models.FileField(default=None, null=True, upload_to='viasus'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imgField',
            field=models.ImageField(default=None, null=True, upload_to='staticfiles/'),
        ),
    ]
