# Generated by Django 5.0.2 on 2024-07-29 23:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_imgcloud_alter_producto_imgfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ownImages',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='ownImage'),
        ),
    ]
