# Generated by Django 5.0.2 on 2024-07-30 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_producto_ownimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='ownImages',
            new_name='ownImage',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imgCloud',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imgField',
        ),
    ]
