# Generated by Django 5.0.2 on 2024-07-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_rename_ownimages_producto_ownimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ownImage',
        ),
    ]
