# Generated by Django 5.0.2 on 2024-07-30 00:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_remove_producto_ownimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgCloud',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='imgCloud'),
        ),
    ]
