# Generated by Django 5.0.2 on 2024-07-30 16:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_producto_imgcloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imgCloud',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='imgCloud'),
        ),
    ]
