# Generated by Django 4.2.3 on 2024-02-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(default=None, max_length=999)),
                ('telefono', models.CharField(default=None, max_length=20)),
                ('correo', models.CharField(default=None, max_length=13)),
            ],
        ),
    ]
