# Generated by Django 4.2.3 on 2024-02-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
