# Generated by Django 4.2.3 on 2024-03-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_activo'),
        ('carro', '0005_pedido_pedididoproducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedididoProducto',
            new_name='PedidoProducto',
        ),
    ]
