# Generated by Django 4.2.3 on 2024-03-06 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0006_rename_pedididoproducto_pedidoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
