# Generated by Django 4.2.3 on 2024-03-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0007_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
