# Generated by Django 5.0.2 on 2024-03-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0008_alter_pedido_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha',
            new_name='fecha_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(default=None),
        ),
    ]
