# Generated by Django 5.0.2 on 2024-03-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0011_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(),
        ),
    ]
