# Generated by Django 5.0.2 on 2024-03-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0012_alter_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
