# Generated by Django 5.0.2 on 2024-03-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0013_alter_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
