# Generated by Django 5.0.2 on 2024-03-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0014_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comentarios',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
