# Generated by Django 5.0.2 on 2024-07-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0016_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
